name: 🚀 Deploy to Reg.ru

on:
  push:
    branches: [ "main" ] # Запускать деплой только при пуше в ветку main

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # (ОПЦИОНАЛЬНО) Если ваш сайт требует сборки (например, на Node.js, Laravel)
    # - name: 📦 Install dependencies
    #   run: npm install

    # - name: 🔨 Build project
    #   run: npm run build

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./ # Папка с файлами для загрузки (после сборки укажите папку сборки, например 'dist/')
        server-dir: ${{ secrets.FTP_REMOTE_PATH }}
